#############################################################################
# Makefile for building: Gestionale
# Generated by qmake (2.01a) (Qt 4.8.4) on: ven gen 3 12:27:45 2014
# Project:  Gestionale.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Gestionale.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I. -ImoduleAgenti -ImoduleAnagrafica -Iutils -ImoduleAzienda -ImoduleMagazzino -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = connectionsetupdialog.cpp \
		error.cpp \
		logindialog.cpp \
		main.cpp \
		mainwindow.cpp \
		tablesetupdialog.cpp \
		moduleAgenti/agentiadddialog.cpp \
		moduleAgenti/agentiviewdialog.cpp \
		moduleAnagrafica/anagraficaadddialog.cpp \
		moduleAnagrafica/anagraficawindow.cpp \
		moduleAnagrafica/optionsanagraficadialog.cpp \
		moduleAzienda/aziendadialog.cpp \
		moduleMagazzino/articolodialog.cpp \
		moduleMagazzino/magazzinowindow.cpp \
		utils/controllodati.cpp \
		utils/simpledialogs.cpp moc_connectionsetupdialog.cpp \
		moc_logindialog.cpp \
		moc_mainwindow.cpp \
		moc_tablesetupdialog.cpp \
		moc_agentiadddialog.cpp \
		moc_agentiviewdialog.cpp \
		moc_anagraficaadddialog.cpp \
		moc_anagraficawindow.cpp \
		moc_optionsanagraficadialog.cpp \
		moc_aziendadialog.cpp \
		moc_articolodialog.cpp \
		moc_magazzinowindow.cpp
OBJECTS       = connectionsetupdialog.o \
		error.o \
		logindialog.o \
		main.o \
		mainwindow.o \
		tablesetupdialog.o \
		agentiadddialog.o \
		agentiviewdialog.o \
		anagraficaadddialog.o \
		anagraficawindow.o \
		optionsanagraficadialog.o \
		aziendadialog.o \
		articolodialog.o \
		magazzinowindow.o \
		controllodati.o \
		simpledialogs.o \
		moc_connectionsetupdialog.o \
		moc_logindialog.o \
		moc_mainwindow.o \
		moc_tablesetupdialog.o \
		moc_agentiadddialog.o \
		moc_agentiviewdialog.o \
		moc_anagraficaadddialog.o \
		moc_anagraficawindow.o \
		moc_optionsanagraficadialog.o \
		moc_aziendadialog.o \
		moc_articolodialog.o \
		moc_magazzinowindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Gestionale.pro
QMAKE_TARGET  = Gestionale
DESTDIR       = 
TARGET        = Gestionale

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_connectionsetupdialog.h ui_logindialog.h ui_mainwindow.h ui_tablesetupdialog.h ui_agentiadddialog.h ui_agentiviewdialog.h ui_anagraficaadddialog.h ui_anagraficawindow.h ui_optionsanagraficadialog.h ui_aziendadialog.h ui_articolodialog.h ui_magazzinowindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Gestionale.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtSql.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Gestionale.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtSql.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Gestionale.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Gestionale1.0.0 || $(MKDIR) .tmp/Gestionale1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Gestionale1.0.0/ && $(COPY_FILE) --parents connectionsetupdialog.h error.h logindialog.h mainwindow.h tablesetupdialog.h moduleAgenti/agentiadddialog.h moduleAgenti/agentiviewdialog.h moduleAnagrafica/anagraficaadddialog.h moduleAnagrafica/anagraficawindow.h moduleAnagrafica/optionsanagraficadialog.h moduleAzienda/aziendadialog.h moduleMagazzino/articolodialog.h moduleMagazzino/magazzinowindow.h utils/controllodati.h utils/simpledialogs.h .tmp/Gestionale1.0.0/ && $(COPY_FILE) --parents connectionsetupdialog.cpp error.cpp logindialog.cpp main.cpp mainwindow.cpp tablesetupdialog.cpp moduleAgenti/agentiadddialog.cpp moduleAgenti/agentiviewdialog.cpp moduleAnagrafica/anagraficaadddialog.cpp moduleAnagrafica/anagraficawindow.cpp moduleAnagrafica/optionsanagraficadialog.cpp moduleAzienda/aziendadialog.cpp moduleMagazzino/articolodialog.cpp moduleMagazzino/magazzinowindow.cpp utils/controllodati.cpp utils/simpledialogs.cpp .tmp/Gestionale1.0.0/ && $(COPY_FILE) --parents connectionsetupdialog.ui logindialog.ui mainwindow.ui tablesetupdialog.ui moduleAgenti/agentiadddialog.ui moduleAgenti/agentiviewdialog.ui moduleAnagrafica/anagraficaadddialog.ui moduleAnagrafica/anagraficawindow.ui moduleAnagrafica/optionsanagraficadialog.ui moduleAzienda/aziendadialog.ui moduleMagazzino/articolodialog.ui moduleMagazzino/magazzinowindow.ui .tmp/Gestionale1.0.0/ && (cd `dirname .tmp/Gestionale1.0.0` && $(TAR) Gestionale1.0.0.tar Gestionale1.0.0 && $(COMPRESS) Gestionale1.0.0.tar) && $(MOVE) `dirname .tmp/Gestionale1.0.0`/Gestionale1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Gestionale1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_connectionsetupdialog.cpp moc_logindialog.cpp moc_mainwindow.cpp moc_tablesetupdialog.cpp moc_agentiadddialog.cpp moc_agentiviewdialog.cpp moc_anagraficaadddialog.cpp moc_anagraficawindow.cpp moc_optionsanagraficadialog.cpp moc_aziendadialog.cpp moc_articolodialog.cpp moc_magazzinowindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_connectionsetupdialog.cpp moc_logindialog.cpp moc_mainwindow.cpp moc_tablesetupdialog.cpp moc_agentiadddialog.cpp moc_agentiviewdialog.cpp moc_anagraficaadddialog.cpp moc_anagraficawindow.cpp moc_optionsanagraficadialog.cpp moc_aziendadialog.cpp moc_articolodialog.cpp moc_magazzinowindow.cpp
moc_connectionsetupdialog.cpp: connectionsetupdialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) connectionsetupdialog.h -o moc_connectionsetupdialog.cpp

moc_logindialog.cpp: connectionsetupdialog.h \
		logindialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) logindialog.h -o moc_logindialog.cpp

moc_mainwindow.cpp: error.h \
		logindialog.h \
		connectionsetupdialog.h \
		tablesetupdialog.h \
		moduleAgenti/agentiviewdialog.h \
		moduleAgenti/agentiadddialog.h \
		moduleAnagrafica/anagraficawindow.h \
		moduleAnagrafica/anagraficaadddialog.h \
		utils/controllodati.h \
		moduleAnagrafica/optionsanagraficadialog.h \
		moduleAzienda/aziendadialog.h \
		utils/simpledialogs.h \
		moduleMagazzino/magazzinowindow.h \
		moduleMagazzino/articolodialog.h \
		mainwindow.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_tablesetupdialog.cpp: error.h \
		tablesetupdialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) tablesetupdialog.h -o moc_tablesetupdialog.cpp

moc_agentiadddialog.cpp: error.h \
		moduleAgenti/agentiadddialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) moduleAgenti/agentiadddialog.h -o moc_agentiadddialog.cpp

moc_agentiviewdialog.cpp: moduleAgenti/agentiadddialog.h \
		error.h \
		moduleAgenti/agentiviewdialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) moduleAgenti/agentiviewdialog.h -o moc_agentiviewdialog.cpp

moc_anagraficaadddialog.cpp: error.h \
		utils/controllodati.h \
		moduleAgenti/agentiadddialog.h \
		moduleAnagrafica/anagraficaadddialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) moduleAnagrafica/anagraficaadddialog.h -o moc_anagraficaadddialog.cpp

moc_anagraficawindow.cpp: moduleAnagrafica/anagraficaadddialog.h \
		error.h \
		utils/controllodati.h \
		moduleAgenti/agentiadddialog.h \
		moduleAnagrafica/optionsanagraficadialog.h \
		moduleAnagrafica/anagraficawindow.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) moduleAnagrafica/anagraficawindow.h -o moc_anagraficawindow.cpp

moc_optionsanagraficadialog.cpp: moduleAnagrafica/optionsanagraficadialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) moduleAnagrafica/optionsanagraficadialog.h -o moc_optionsanagraficadialog.cpp

moc_aziendadialog.cpp: error.h \
		utils/simpledialogs.h \
		utils/controllodati.h \
		moduleAzienda/aziendadialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) moduleAzienda/aziendadialog.h -o moc_aziendadialog.cpp

moc_articolodialog.cpp: moduleMagazzino/articolodialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) moduleMagazzino/articolodialog.h -o moc_articolodialog.cpp

moc_magazzinowindow.cpp: moduleMagazzino/articolodialog.h \
		moduleMagazzino/magazzinowindow.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) moduleMagazzino/magazzinowindow.h -o moc_magazzinowindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_connectionsetupdialog.h ui_logindialog.h ui_mainwindow.h ui_tablesetupdialog.h ui_agentiadddialog.h ui_agentiviewdialog.h ui_anagraficaadddialog.h ui_anagraficawindow.h ui_optionsanagraficadialog.h ui_aziendadialog.h ui_articolodialog.h ui_magazzinowindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_connectionsetupdialog.h ui_logindialog.h ui_mainwindow.h ui_tablesetupdialog.h ui_agentiadddialog.h ui_agentiviewdialog.h ui_anagraficaadddialog.h ui_anagraficawindow.h ui_optionsanagraficadialog.h ui_aziendadialog.h ui_articolodialog.h ui_magazzinowindow.h
ui_connectionsetupdialog.h: connectionsetupdialog.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic connectionsetupdialog.ui -o ui_connectionsetupdialog.h

ui_logindialog.h: logindialog.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic logindialog.ui -o ui_logindialog.h

ui_mainwindow.h: mainwindow.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_tablesetupdialog.h: tablesetupdialog.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic tablesetupdialog.ui -o ui_tablesetupdialog.h

ui_agentiadddialog.h: moduleAgenti/agentiadddialog.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic moduleAgenti/agentiadddialog.ui -o ui_agentiadddialog.h

ui_agentiviewdialog.h: moduleAgenti/agentiviewdialog.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic moduleAgenti/agentiviewdialog.ui -o ui_agentiviewdialog.h

ui_anagraficaadddialog.h: moduleAnagrafica/anagraficaadddialog.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic moduleAnagrafica/anagraficaadddialog.ui -o ui_anagraficaadddialog.h

ui_anagraficawindow.h: moduleAnagrafica/anagraficawindow.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic moduleAnagrafica/anagraficawindow.ui -o ui_anagraficawindow.h

ui_optionsanagraficadialog.h: moduleAnagrafica/optionsanagraficadialog.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic moduleAnagrafica/optionsanagraficadialog.ui -o ui_optionsanagraficadialog.h

ui_aziendadialog.h: moduleAzienda/aziendadialog.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic moduleAzienda/aziendadialog.ui -o ui_aziendadialog.h

ui_articolodialog.h: moduleMagazzino/articolodialog.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic moduleMagazzino/articolodialog.ui -o ui_articolodialog.h

ui_magazzinowindow.h: moduleMagazzino/magazzinowindow.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic moduleMagazzino/magazzinowindow.ui -o ui_magazzinowindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

connectionsetupdialog.o: connectionsetupdialog.cpp connectionsetupdialog.h \
		ui_connectionsetupdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectionsetupdialog.o connectionsetupdialog.cpp

error.o: error.cpp error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o error.o error.cpp

logindialog.o: logindialog.cpp logindialog.h \
		connectionsetupdialog.h \
		ui_logindialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logindialog.o logindialog.cpp

main.o: main.cpp mainwindow.h \
		error.h \
		logindialog.h \
		connectionsetupdialog.h \
		tablesetupdialog.h \
		moduleAgenti/agentiviewdialog.h \
		moduleAgenti/agentiadddialog.h \
		moduleAnagrafica/anagraficawindow.h \
		moduleAnagrafica/anagraficaadddialog.h \
		utils/controllodati.h \
		moduleAnagrafica/optionsanagraficadialog.h \
		moduleAzienda/aziendadialog.h \
		utils/simpledialogs.h \
		moduleMagazzino/magazzinowindow.h \
		moduleMagazzino/articolodialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		error.h \
		logindialog.h \
		connectionsetupdialog.h \
		tablesetupdialog.h \
		moduleAgenti/agentiviewdialog.h \
		moduleAgenti/agentiadddialog.h \
		moduleAnagrafica/anagraficawindow.h \
		moduleAnagrafica/anagraficaadddialog.h \
		utils/controllodati.h \
		moduleAnagrafica/optionsanagraficadialog.h \
		moduleAzienda/aziendadialog.h \
		utils/simpledialogs.h \
		moduleMagazzino/magazzinowindow.h \
		moduleMagazzino/articolodialog.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

tablesetupdialog.o: tablesetupdialog.cpp tablesetupdialog.h \
		error.h \
		ui_tablesetupdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tablesetupdialog.o tablesetupdialog.cpp

agentiadddialog.o: moduleAgenti/agentiadddialog.cpp moduleAgenti/agentiadddialog.h \
		error.h \
		ui_agentiadddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agentiadddialog.o moduleAgenti/agentiadddialog.cpp

agentiviewdialog.o: moduleAgenti/agentiviewdialog.cpp moduleAgenti/agentiviewdialog.h \
		moduleAgenti/agentiadddialog.h \
		error.h \
		ui_agentiviewdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agentiviewdialog.o moduleAgenti/agentiviewdialog.cpp

anagraficaadddialog.o: moduleAnagrafica/anagraficaadddialog.cpp moduleAnagrafica/anagraficaadddialog.h \
		error.h \
		utils/controllodati.h \
		moduleAgenti/agentiadddialog.h \
		ui_anagraficaadddialog.h \
		utils/simpledialogs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o anagraficaadddialog.o moduleAnagrafica/anagraficaadddialog.cpp

anagraficawindow.o: moduleAnagrafica/anagraficawindow.cpp moduleAnagrafica/anagraficawindow.h \
		moduleAnagrafica/anagraficaadddialog.h \
		error.h \
		utils/controllodati.h \
		moduleAgenti/agentiadddialog.h \
		moduleAnagrafica/optionsanagraficadialog.h \
		ui_anagraficawindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o anagraficawindow.o moduleAnagrafica/anagraficawindow.cpp

optionsanagraficadialog.o: moduleAnagrafica/optionsanagraficadialog.cpp moduleAnagrafica/optionsanagraficadialog.h \
		ui_optionsanagraficadialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionsanagraficadialog.o moduleAnagrafica/optionsanagraficadialog.cpp

aziendadialog.o: moduleAzienda/aziendadialog.cpp moduleAzienda/aziendadialog.h \
		error.h \
		utils/simpledialogs.h \
		utils/controllodati.h \
		ui_aziendadialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aziendadialog.o moduleAzienda/aziendadialog.cpp

articolodialog.o: moduleMagazzino/articolodialog.cpp moduleMagazzino/articolodialog.h \
		ui_articolodialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o articolodialog.o moduleMagazzino/articolodialog.cpp

magazzinowindow.o: moduleMagazzino/magazzinowindow.cpp moduleMagazzino/magazzinowindow.h \
		moduleMagazzino/articolodialog.h \
		ui_magazzinowindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o magazzinowindow.o moduleMagazzino/magazzinowindow.cpp

controllodati.o: utils/controllodati.cpp utils/controllodati.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controllodati.o utils/controllodati.cpp

simpledialogs.o: utils/simpledialogs.cpp utils/simpledialogs.h \
		error.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simpledialogs.o utils/simpledialogs.cpp

moc_connectionsetupdialog.o: moc_connectionsetupdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connectionsetupdialog.o moc_connectionsetupdialog.cpp

moc_logindialog.o: moc_logindialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logindialog.o moc_logindialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_tablesetupdialog.o: moc_tablesetupdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tablesetupdialog.o moc_tablesetupdialog.cpp

moc_agentiadddialog.o: moc_agentiadddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_agentiadddialog.o moc_agentiadddialog.cpp

moc_agentiviewdialog.o: moc_agentiviewdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_agentiviewdialog.o moc_agentiviewdialog.cpp

moc_anagraficaadddialog.o: moc_anagraficaadddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_anagraficaadddialog.o moc_anagraficaadddialog.cpp

moc_anagraficawindow.o: moc_anagraficawindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_anagraficawindow.o moc_anagraficawindow.cpp

moc_optionsanagraficadialog.o: moc_optionsanagraficadialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optionsanagraficadialog.o moc_optionsanagraficadialog.cpp

moc_aziendadialog.o: moc_aziendadialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aziendadialog.o moc_aziendadialog.cpp

moc_articolodialog.o: moc_articolodialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_articolodialog.o moc_articolodialog.cpp

moc_magazzinowindow.o: moc_magazzinowindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_magazzinowindow.o moc_magazzinowindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

