BEGIN;
INSERT INTO provincia(descr, sigla) VALUES('Agrigento', 'AG');
INSERT INTO provincia(descr, sigla) VALUES('Alessandria', 'AL');
INSERT INTO provincia(descr, sigla) VALUES('Ancona', 'AN');
INSERT INTO provincia(descr, sigla) VALUES('Aosta', 'AO');
INSERT INTO provincia(descr, sigla) VALUES('Arezzo', 'AR');
INSERT INTO provincia(descr, sigla) VALUES('Ascoli Piceno', 'AP');
INSERT INTO provincia(descr, sigla) VALUES('Asti', 'AT');
INSERT INTO provincia(descr, sigla) VALUES('Avellino', 'AV');
INSERT INTO provincia(descr, sigla) VALUES('Bari', 'BA');
INSERT INTO provincia(descr, sigla) VALUES('Barletta-Andria-Trani', 'BT');
INSERT INTO provincia(descr, sigla) VALUES('Belluno', 'BL');
INSERT INTO provincia(descr, sigla) VALUES('Benevento', 'BN');
INSERT INTO provincia(descr, sigla) VALUES('Bergamo', 'BG');
INSERT INTO provincia(descr, sigla) VALUES('Biella', 'BI');
INSERT INTO provincia(descr, sigla) VALUES('Bologna', 'BO');
INSERT INTO provincia(descr, sigla) VALUES('Bolzano', 'BZ');
INSERT INTO provincia(descr, sigla) VALUES('Brescia', 'BS');
INSERT INTO provincia(descr, sigla) VALUES('Brindisi', 'BR');
INSERT INTO provincia(descr, sigla) VALUES('Cagliari','CA');
INSERT INTO provincia(descr, sigla) VALUES('Caltanissetta','CL');
INSERT INTO provincia(descr, sigla) VALUES('Campobasso','CB');
INSERT INTO provincia(descr, sigla) VALUES('Carbonia-Iglesias','CI');
INSERT INTO provincia(descr, sigla) VALUES('Caserta','CE');
INSERT INTO provincia(descr, sigla) VALUES('Catania','CT');
INSERT INTO provincia(descr, sigla) VALUES('Catanzaro','CZ');
INSERT INTO provincia(descr, sigla) VALUES('Chieti','CH');
INSERT INTO provincia(descr, sigla) VALUES('Como','CO');
INSERT INTO provincia(descr, sigla) VALUES('Cosenza','CS');
INSERT INTO provincia(descr, sigla) VALUES('Cremona','CR');
INSERT INTO provincia(descr, sigla) VALUES('Crotone','KR');
INSERT INTO provincia(descr, sigla) VALUES('Cuneo','CN');
INSERT INTO provincia(descr, sigla) VALUES('Enna','EN');
INSERT INTO provincia(descr, sigla) VALUES('Fermo','FM');
INSERT INTO provincia(descr, sigla) VALUES('Ferrara','FE');
INSERT INTO provincia(descr, sigla) VALUES('Firenze','FI');
INSERT INTO provincia(descr, sigla) VALUES('Foggia','FG');
INSERT INTO provincia(descr, sigla) VALUES('Forlì-Cesena','FC');
INSERT INTO provincia(descr, sigla) VALUES('Frosinone','FR');
INSERT INTO provincia(descr, sigla) VALUES('Genova','GE');
INSERT INTO provincia(descr, sigla) VALUES('Gorizia','GO');
INSERT INTO provincia(descr, sigla) VALUES('Grosseto','GR');
INSERT INTO provincia(descr, sigla) VALUES('Imperia','IM');
INSERT INTO provincia(descr, sigla) VALUES('Isernia','IS');
INSERT INTO provincia(descr, sigla) VALUES('La Spezia','SP');
INSERT INTO provincia(descr, sigla) VALUES('L''Aquila','AQ');
INSERT INTO provincia(descr, sigla) VALUES('Latina','LT');
INSERT INTO provincia(descr, sigla) VALUES('Lecce','LE');
INSERT INTO provincia(descr, sigla) VALUES('Lecco','LC');
INSERT INTO provincia(descr, sigla) VALUES('Livorno','LI');
INSERT INTO provincia(descr, sigla) VALUES('Lodi','LO');
INSERT INTO provincia(descr, sigla) VALUES('Lucca','LU');
INSERT INTO provincia(descr, sigla) VALUES('Macerata','MC');
INSERT INTO provincia(descr, sigla) VALUES('Mantova','MN');
INSERT INTO provincia(descr, sigla) VALUES('Massa-Carrara','MS');
INSERT INTO provincia(descr, sigla) VALUES('Matera','MT');
INSERT INTO provincia(descr, sigla) VALUES('Messina','ME');
INSERT INTO provincia(descr, sigla) VALUES('Milano','MI');
INSERT INTO provincia(descr, sigla) VALUES('Modena','MO');
INSERT INTO provincia(descr, sigla) VALUES('Monza e della Brianza','MB');
INSERT INTO provincia(descr, sigla) VALUES('Napoli','NA');
INSERT INTO provincia(descr, sigla) VALUES('Novara','NO');
INSERT INTO provincia(descr, sigla) VALUES('Nuoro','NU');
INSERT INTO provincia(descr, sigla) VALUES('Olbia-Tempio','OT');
INSERT INTO provincia(descr, sigla) VALUES('Oristano','OR');
INSERT INTO provincia(descr, sigla) VALUES('Padova','PD');
INSERT INTO provincia(descr, sigla) VALUES('Palermo','PA');
INSERT INTO provincia(descr, sigla) VALUES('Parma','PR');
INSERT INTO provincia(descr, sigla) VALUES('Pavia','PV');
INSERT INTO provincia(descr, sigla) VALUES('Perugia','PG');
INSERT INTO provincia(descr, sigla) VALUES('Pesaro e Urbino','PU');
INSERT INTO provincia(descr, sigla) VALUES('Pescara','PE');
INSERT INTO provincia(descr, sigla) VALUES('Piacenza','PC');
INSERT INTO provincia(descr, sigla) VALUES('Pisa','PI');
INSERT INTO provincia(descr, sigla) VALUES('Pistoia','PT');
INSERT INTO provincia(descr, sigla) VALUES('Pordenone','PN');
INSERT INTO provincia(descr, sigla) VALUES('Potenza','PZ');
INSERT INTO provincia(descr, sigla) VALUES('Prato','PO');
INSERT INTO provincia(descr, sigla) VALUES('Ragusa','RG');
INSERT INTO provincia(descr, sigla) VALUES('Ravenna','RA');
INSERT INTO provincia(descr, sigla) VALUES('Reggio Calabria','RC');
INSERT INTO provincia(descr, sigla) VALUES('Reggio Emilia','RE');
INSERT INTO provincia(descr, sigla) VALUES('Rieti','RI');
INSERT INTO provincia(descr, sigla) VALUES('Rimini','RN');
INSERT INTO provincia(descr, sigla) VALUES('Roma','RM');
INSERT INTO provincia(descr, sigla) VALUES('Rovigo','RO');
INSERT INTO provincia(descr, sigla) VALUES('Salerno','SA');
INSERT INTO provincia(descr, sigla) VALUES('Medio Campidano','VS');
INSERT INTO provincia(descr, sigla) VALUES('Sassari','SS');
INSERT INTO provincia(descr, sigla) VALUES('Savona','SV');
INSERT INTO provincia(descr, sigla) VALUES('Siena','SI');
INSERT INTO provincia(descr, sigla) VALUES('Siracusa','SR');
INSERT INTO provincia(descr, sigla) VALUES('Sondrio','SO');
INSERT INTO provincia(descr, sigla) VALUES('Taranto','TA');
INSERT INTO provincia(descr, sigla) VALUES('Teramo','TE');
INSERT INTO provincia(descr, sigla) VALUES('Terni','TR');
INSERT INTO provincia(descr, sigla) VALUES('Torino','TO');
INSERT INTO provincia(descr, sigla) VALUES('Ogliastra','OG');
INSERT INTO provincia(descr, sigla) VALUES('Trapani','TP');
INSERT INTO provincia(descr, sigla) VALUES('Trento','TN');
INSERT INTO provincia(descr, sigla) VALUES('Treviso','TV');
INSERT INTO provincia(descr, sigla) VALUES('Trieste','TS');
INSERT INTO provincia(descr, sigla) VALUES('Udine','UD');
INSERT INTO provincia(descr, sigla) VALUES('Varese','VA');
INSERT INTO provincia(descr, sigla) VALUES('Venezia','VE');
INSERT INTO provincia(descr, sigla) VALUES('Verbano-Cusio-Ossola','VB');
INSERT INTO provincia(descr, sigla) VALUES('Vercelli','VC');
INSERT INTO provincia(descr, sigla) VALUES('Verona','VR');
INSERT INTO provincia(descr, sigla) VALUES('Vibo Valentia','VV');
INSERT INTO provincia(descr, sigla) VALUES('Vicenza','VI');
INSERT INTO provincia(descr, sigla) VALUES('Viterbo','VT');
COMMIT;
