INSERT INTO stato(descr, sigla) VALUES('Andorra', 'AD'); 
INSERT INTO stato(descr, sigla) VALUES('Albania', 'AL');
INSERT INTO stato(descr, sigla) VALUES('Argentina', 'AR');
INSERT INTO stato(descr, sigla) VALUES('Austria', 'AT');
INSERT INTO stato(descr, sigla) VALUES('Australia', 'AU');	
INSERT INTO stato(descr, sigla) VALUES('Belgio ', 'BE');	
INSERT INTO stato(descr, sigla) VALUES('Bulgaria', 'BG');	
INSERT INTO stato(descr, sigla) VALUES('Francia', 'FR');
INSERT INTO stato(descr, sigla) VALUES('Bosnia ed Erzegovina', 'BA');
INSERT INTO stato(descr, sigla) VALUES('Emirati Arabi Uniti', 'AE');	
INSERT INTO stato(descr, sigla) VALUES('Afghanistan', 'AF');
INSERT INTO stato(descr, sigla) VALUES('Antigua e Barbuda', 'AG');
INSERT INTO stato(descr, sigla) VALUES('Anguilla', 'AI');
INSERT INTO stato(descr, sigla) VALUES('Armenia', 'AM');
INSERT INTO stato(descr, sigla) VALUES('Angola', 'AO');
INSERT INTO stato(descr, sigla) VALUES('Antartide', 'AQ');
INSERT INTO stato(descr, sigla) VALUES('Samoa Americane', 'AS');
INSERT INTO stato(descr, sigla) VALUES('Aruba', 'AW');
INSERT INTO stato(descr, sigla) VALUES('Azerbaigian', 'AZ');	
INSERT INTO stato(descr, sigla) VALUES('Barbados', 'BB');
INSERT INTO stato(descr, sigla) VALUES('Bangladesh', 'BD');
INSERT INTO stato(descr, sigla) VALUES('Burkina Faso', 'BF');
INSERT INTO stato(descr, sigla) VALUES('Bahrein', 'BH');
INSERT INTO stato(descr, sigla) VALUES('Burundi', 'BI');
INSERT INTO stato(descr, sigla) VALUES('Benin', 'BJ');
INSERT INTO stato(descr, sigla) VALUES('Saint-Barthélemy', 'BL');
INSERT INTO stato(descr, sigla) VALUES('Bermuda', 'BM');
INSERT INTO stato(descr, sigla) VALUES('Brunei', 'BN');
INSERT INTO stato(descr, sigla) VALUES('Bolivia', 'BO');
INSERT INTO stato(descr, sigla) VALUES('Isole BES', 'BQ');
INSERT INTO stato(descr, sigla) VALUES('Brasile', 'BR');
INSERT INTO stato(descr, sigla) VALUES('Bahamas', 'BS');
INSERT INTO stato(descr, sigla) VALUES('Bhutan', 'BT');
INSERT INTO stato(descr, sigla) VALUES('Isola Bouvet', 'BV');
INSERT INTO stato(descr, sigla) VALUES('Botswana', 'BW');
INSERT INTO stato(descr, sigla) VALUES('Bielorussia', 'BY');
INSERT INTO stato(descr, sigla) VALUES('Belize', 'BZ');
INSERT INTO stato(descr, sigla) VALUES('Canada', 'CA');
INSERT INTO stato(descr, sigla) VALUES('Isole Cocos e Keeling', 'CC');
INSERT INTO stato(descr, sigla) VALUES('Repubblica Democratica del Congo', 'CD');
INSERT INTO stato(descr, sigla) VALUES('Repubblica Centrafricana', 'CF');
INSERT INTO stato(descr, sigla) VALUES('Repubblica del Congo', 'CG');
INSERT INTO stato(descr, sigla) VALUES('Svizzera' , 'CH');
INSERT INTO stato(descr, sigla) VALUES('Costa d''Avorio' , 'CI');
INSERT INTO stato(descr, sigla) VALUES('Isole Cook' , 'CK');
INSERT INTO stato(descr, sigla) VALUES('Cile' , 'CL');
INSERT INTO stato(descr, sigla) VALUES('Camerun' , 'CM');
INSERT INTO stato(descr, sigla) VALUES('Cina', 'CN');
INSERT INTO stato(descr, sigla) VALUES('Colombia' , 'CO');
INSERT INTO stato(descr, sigla) VALUES('Costa Rica' , 'CR');
INSERT INTO stato(descr, sigla) VALUES('Cuba' , 'CU');
INSERT INTO stato(descr, sigla) VALUES('Capo Verde' , 'CV');
INSERT INTO stato(descr, sigla) VALUES('Isola del Natale' , 'CX');
INSERT INTO stato(descr, sigla) VALUES('Cipro' , 'CY');
INSERT INTO stato(descr, sigla) VALUES('Cechia' , 'CZ');
INSERT INTO stato(descr, sigla) VALUES('Germania' , 'DE');
INSERT INTO stato(descr, sigla) VALUES('Gibuti' , 'DJ');
INSERT INTO stato(descr, sigla) VALUES('Danimarca' , 'DK');
INSERT INTO stato(descr, sigla) VALUES('Dominica' , 'DM');
INSERT INTO stato(descr, sigla) VALUES('Repubblica Dominicana' , 'DO');
INSERT INTO stato(descr, sigla) VALUES('Algeria' , 'DZ');
INSERT INTO stato(descr, sigla) VALUES('Ecuador' , 'EC');
INSERT INTO stato(descr, sigla) VALUES('Estonia' , 'EE');
INSERT INTO stato(descr, sigla) VALUES('Egitto' , 'EG');
INSERT INTO stato(descr, sigla) VALUES('Sahara Occidentale', 'EH');
INSERT INTO stato(descr, sigla) VALUES('Eritrea' , 'ER');
INSERT INTO stato(descr, sigla) VALUES('Spagna' , 'ES');
INSERT INTO stato(descr, sigla) VALUES('Etiopia' , 'ET');
INSERT INTO stato(descr, sigla) VALUES('Finlandia' , 'FI');
INSERT INTO stato(descr, sigla) VALUES('Figi' , 'FJ');
INSERT INTO stato(descr, sigla) VALUES('Isole Falkland' , 'FK');
INSERT INTO stato(descr, sigla) VALUES('Stati Federati di Micronesia' , 'FM');
INSERT INTO stato(descr, sigla) VALUES('Gabon' , 'GA');
INSERT INTO stato(descr, sigla) VALUES('Regno Unito', 'GB'); 
INSERT INTO stato(descr, sigla) VALUES('Grenada' , 'GD');
INSERT INTO stato(descr, sigla) VALUES('Georgia' , 'GE');
INSERT INTO stato(descr, sigla) VALUES('Guyana francese' , 'GF');
INSERT INTO stato(descr, sigla) VALUES('Guernsey' , 'GG');
INSERT INTO stato(descr, sigla) VALUES('Ghana', 'GH');	
INSERT INTO stato(descr, sigla) VALUES('Gibilterra' , 'GI');
INSERT INTO stato(descr, sigla) VALUES('Groenlandia' , 'GL');
INSERT INTO stato(descr, sigla) VALUES('Gambia' , 'GM');
INSERT INTO stato(descr, sigla) VALUES('Guinea' , 'GN');
INSERT INTO stato(descr, sigla) VALUES('Guadalupa' , 'GP');
INSERT INTO stato(descr, sigla) VALUES('Guinea Equatoriale' , 'GQ');
INSERT INTO stato(descr, sigla) VALUES('Grecia' , 'GR');
INSERT INTO stato(descr, sigla) VALUES('Guatemala' , 'GT');
INSERT INTO stato(descr, sigla) VALUES('Guam' , 'GU');
INSERT INTO stato(descr, sigla) VALUES('Guinea-Bissau' , 'GW');
INSERT INTO stato(descr, sigla) VALUES('Guyana' , 'GY');
INSERT INTO stato(descr, sigla) VALUES('Hong Kong' , 'HK');
INSERT INTO stato(descr, sigla) VALUES('Honduras' , 'HN');
INSERT INTO stato(descr, sigla) VALUES('Croazia' , 'HR');
INSERT INTO stato(descr, sigla) VALUES('Haiti' , 'HT');
INSERT INTO stato(descr, sigla) VALUES('Ungheria' , 'HU');
INSERT INTO stato(descr, sigla) VALUES('Indonesia' , 'ID');
INSERT INTO stato(descr, sigla) VALUES('Irlanda' , 'IE');
INSERT INTO stato(descr, sigla) VALUES('Israele' , 'IL');
INSERT INTO stato(descr, sigla) VALUES('Isola di Man' , 'IM');
INSERT INTO stato(descr, sigla) VALUES('India' , 'IN');
INSERT INTO stato(descr, sigla) VALUES('Iraq' , 'IQ');
INSERT INTO stato(descr, sigla) VALUES('Iran' , 'IR');
INSERT INTO stato(descr, sigla) VALUES('Islanda' , 'IS');
INSERT INTO stato(descr, sigla) VALUES('Italia' , 'IT');
INSERT INTO stato(descr, sigla) VALUES('Jersey' , 'JE');
INSERT INTO stato(descr, sigla) VALUES('Giamaica' , 'JM');
INSERT INTO stato(descr, sigla) VALUES('Giordania' , 'JO');
INSERT INTO stato(descr, sigla) VALUES('Giappone' , 'JP');
INSERT INTO stato(descr, sigla) VALUES('Kenya' , 'KE');
INSERT INTO stato(descr, sigla) VALUES('Kirghizistan' , 'KG');
INSERT INTO stato(descr, sigla) VALUES('Cambogia' , 'KH');
INSERT INTO stato(descr, sigla) VALUES('Kiribati' , 'KI');
INSERT INTO stato(descr, sigla) VALUES('Comore' , 'KM');
INSERT INTO stato(descr, sigla) VALUES('Saint Kitts e Nevis' , 'KN');
INSERT INTO stato(descr, sigla) VALUES('Corea del Nord' , 'KP');
INSERT INTO stato(descr, sigla) VALUES('Corea del Sud' , 'KR');
INSERT INTO stato(descr, sigla) VALUES('Kuwait' , 'KW');
INSERT INTO stato(descr, sigla) VALUES('Isole Cayman' , 'KY');
INSERT INTO stato(descr, sigla) VALUES('Kazakistan' , 'KZ');--
INSERT INTO stato(descr, sigla) VALUES('Laos' , 'LA');
INSERT INTO stato(descr, sigla) VALUES('Libano' , 'LB');
INSERT INTO stato(descr, sigla) VALUES('Santa Lucia' , 'LC');
INSERT INTO stato(descr, sigla) VALUES('Liechtenstein' , 'LI');
INSERT INTO stato(descr, sigla) VALUES('Sri Lanka' , 'LK');
INSERT INTO stato(descr, sigla) VALUES('Liberia' , 'LR');
INSERT INTO stato(descr, sigla) VALUES('Lesotho' , 'LS');
INSERT INTO stato(descr, sigla) VALUES('Lituania' , 'LT');
INSERT INTO stato(descr, sigla) VALUES('Lussemburgo' , 'LU');
INSERT INTO stato(descr, sigla) VALUES('Lettonia' , 'LV');
INSERT INTO stato(descr, sigla) VALUES('Libia', 'LY');	
INSERT INTO stato(descr, sigla) VALUES('Marocco' , 'MA');
INSERT INTO stato(descr, sigla) VALUES('Monaco' , 'MC');
INSERT INTO stato(descr, sigla) VALUES('Moldavia' , 'MD');
INSERT INTO stato(descr, sigla) VALUES('Montenegro' , 'ME');
INSERT INTO stato(descr, sigla) VALUES('Saint-Martin' , 'MF');
INSERT INTO stato(descr, sigla) VALUES('Madagascar' , 'MG');
INSERT INTO stato(descr, sigla) VALUES('Isole Marshall' , 'MH');
INSERT INTO stato(descr, sigla) VALUES('Macedonia' , 'MK');
INSERT INTO stato(descr, sigla) VALUES('Mali' , 'ML');
INSERT INTO stato(descr, sigla) VALUES('Birmania', 'MM');
INSERT INTO stato(descr, sigla) VALUES('Mongolia' , 'MN');
INSERT INTO stato(descr, sigla) VALUES('Macao' , 'MO');
INSERT INTO stato(descr, sigla) VALUES('Isole Marianne' , 'MP');
INSERT INTO stato(descr, sigla) VALUES('Martinica' , 'MQ');
INSERT INTO stato(descr, sigla) VALUES('Mauritania' , 'MR');
INSERT INTO stato(descr, sigla) VALUES('Montserrat' , 'MS');
INSERT INTO stato(descr, sigla) VALUES('Malta' , 'MT');
INSERT INTO stato(descr, sigla) VALUES('Mauritius' , 'MU');
INSERT INTO stato(descr, sigla) VALUES('Maldive' , 'MV');
INSERT INTO stato(descr, sigla) VALUES('Malawi' , 'MW');
INSERT INTO stato(descr, sigla) VALUES('Messico' , 'MX');
INSERT INTO stato(descr, sigla) VALUES('Malesia' , 'MY');
INSERT INTO stato(descr, sigla) VALUES('Mozambico' , 'MZ');
INSERT INTO stato(descr, sigla) VALUES('Namibia' , 'NA');
INSERT INTO stato(descr, sigla) VALUES('Nuova Caledonia' , 'NC');
INSERT INTO stato(descr, sigla) VALUES('Niger' , 'NE');
INSERT INTO stato(descr, sigla) VALUES('Isola Norfolk' , 'NF');
INSERT INTO stato(descr, sigla) VALUES('Nigeria' , 'NG');
INSERT INTO stato(descr, sigla) VALUES('Nicaragua' , 'NI');
INSERT INTO stato(descr, sigla) VALUES('Paesi Bassi' , 'NL');
INSERT INTO stato(descr, sigla) VALUES('Norvegia' , 'NO');
INSERT INTO stato(descr, sigla) VALUES('Nepal' , 'NP');
INSERT INTO stato(descr, sigla) VALUES('Nauru' , 'NR');
INSERT INTO stato(descr, sigla) VALUES('Niue' , 'NU');
INSERT INTO stato(descr, sigla) VALUES('Nuova Zelanda' , 'NZ');
INSERT INTO stato(descr, sigla) VALUES('Oman' , 'OM');
INSERT INTO stato(descr, sigla) VALUES('Panama' , 'PA');
INSERT INTO stato(descr, sigla) VALUES('Perù' , 'PE');
INSERT INTO stato(descr, sigla) VALUES('Polinesia Francese', 'PF');
INSERT INTO stato(descr, sigla) VALUES('Papua Nuova Guinea' , 'PG');
INSERT INTO stato(descr, sigla) VALUES('Filippine' , 'PH');
INSERT INTO stato(descr, sigla) VALUES('Pakistan' , 'PK');
INSERT INTO stato(descr, sigla) VALUES('Polonia' , 'PL');
INSERT INTO stato(descr, sigla) VALUES('Porto Rico' , 'PR');
INSERT INTO stato(descr, sigla) VALUES('Stato di Palestina' , 'PS');
INSERT INTO stato(descr, sigla) VALUES('Portogallo' , 'PT');
INSERT INTO stato(descr, sigla) VALUES('Palau' , 'PW');
INSERT INTO stato(descr, sigla) VALUES('Paraguay' , 'PY');
INSERT INTO stato(descr, sigla) VALUES('Qatar' , 'QA');
INSERT INTO stato(descr, sigla) VALUES('Riunione' , 'RE');
INSERT INTO stato(descr, sigla) VALUES('Romania' , 'RO');
INSERT INTO stato(descr, sigla) VALUES('Serbia' , 'RS');
INSERT INTO stato(descr, sigla) VALUES('Russia' , 'RU');
INSERT INTO stato(descr, sigla) VALUES('Ruanda' , 'RW');
INSERT INTO stato(descr, sigla) VALUES('Arabia Saudita' , 'SA');
INSERT INTO stato(descr, sigla) VALUES('Isole Salomone' , 'SB');
INSERT INTO stato(descr, sigla) VALUES('Seychelles' , 'SC');
INSERT INTO stato(descr, sigla) VALUES('Sudan' , 'SD');
INSERT INTO stato(descr, sigla) VALUES('Svezia' , 'SE');
INSERT INTO stato(descr, sigla) VALUES('Singapore' , 'SG');
INSERT INTO stato(descr, sigla) VALUES('Sant''Elena' , 'SH');
INSERT INTO stato(descr, sigla) VALUES('Slovenia' , 'SI');
INSERT INTO stato(descr, sigla) VALUES('Slovacchia', 'SK');
INSERT INTO stato(descr, sigla) VALUES('Sierra Leone' , 'SL');
INSERT INTO stato(descr, sigla) VALUES('San Marino' , 'SM');
INSERT INTO stato(descr, sigla) VALUES('Senegal' , 'SN');
INSERT INTO stato(descr, sigla) VALUES('Somalia' , 'SO');
INSERT INTO stato(descr, sigla) VALUES('Suriname' , 'SR');
INSERT INTO stato(descr, sigla) VALUES('Sudan del Sud' , 'SS');
INSERT INTO stato(descr, sigla) VALUES('São Tomé e Príncipe' , 'ST');
INSERT INTO stato(descr, sigla) VALUES('El Salvador' , 'SV');
INSERT INTO stato(descr, sigla) VALUES('Sint Maarten', 'SX');
INSERT INTO stato(descr, sigla) VALUES('Siria' , 'SY');
INSERT INTO stato(descr, sigla) VALUES('Swaziland' , 'SZ');
INSERT INTO stato(descr, sigla) VALUES('Ciad' , 'TD');
INSERT INTO stato(descr, sigla) VALUES('Togo' , 'TG');
INSERT INTO stato(descr, sigla) VALUES('Thailandia' , 'TH');
INSERT INTO stato(descr, sigla) VALUES('Tagikistan' , 'TJ');
INSERT INTO stato(descr, sigla) VALUES('Tokelau' , 'TK');
INSERT INTO stato(descr, sigla) VALUES('Timor Est', 'TL');
INSERT INTO stato(descr, sigla) VALUES('Turkmenistan' , 'TM');
INSERT INTO stato(descr, sigla) VALUES('Tunisia' , 'TN');
INSERT INTO stato(descr, sigla) VALUES('Tonga' , 'TO');
INSERT INTO stato(descr, sigla) VALUES('Turchia' , 'TR');
INSERT INTO stato(descr, sigla) VALUES('Trinidad e Tobago' , 'TT');
INSERT INTO stato(descr, sigla) VALUES('Tuvalu' , 'TV');
INSERT INTO stato(descr, sigla) VALUES('Taiwan', 'TW');
INSERT INTO stato(descr, sigla) VALUES('Tanzania' , 'TZ');
INSERT INTO stato(descr, sigla) VALUES('Ucraina' , 'UA');
INSERT INTO stato(descr, sigla) VALUES('Uganda' , 'UG');
INSERT INTO stato(descr, sigla) VALUES('Stati Uniti d''America' , 'US');
INSERT INTO stato(descr, sigla) VALUES('Uruguay' , 'UY');
INSERT INTO stato(descr, sigla) VALUES('Uzbekistan' , 'UZ');
INSERT INTO stato(descr, sigla) VALUES('Città del Vaticano' , 'VA');
INSERT INTO stato(descr, sigla) VALUES('Saint Vincent e Grenadine' , 'VC');
INSERT INTO stato(descr, sigla) VALUES('Venezuela' , 'VE');
INSERT INTO stato(descr, sigla) VALUES('Vietnam' , 'VN');
INSERT INTO stato(descr, sigla) VALUES('Vanuatu' , 'VU');
INSERT INTO stato(descr, sigla) VALUES('Wallis e Futuna' , 'WF');
INSERT INTO stato(descr, sigla) VALUES('Samoa', 'WS');
INSERT INTO stato(descr, sigla) VALUES('Yemen' , 'YE');
INSERT INTO stato(descr, sigla) VALUES('Mayotte' , 'YT');
INSERT INTO stato(descr, sigla) VALUES('Sudafrica' , 'ZA');
INSERT INTO stato(descr, sigla) VALUES('Zambia' , 'ZM');
INSERT INTO stato(descr, sigla) VALUES('Zimbabwe', 'ZW');
