BEGIN;
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Contanti', 'MP01');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Assegno', 'MP02');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Assegno circolare', 'MP03');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Contanti presso Tesoreria', 'MP04');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Bonifico', 'MP05');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Vaglia cambiario', 'MP06');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Bollettino bancario', 'MP07');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Carta di pagamento','MP08');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'RID', 'MP09');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'RID utenze', 'MP10');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'RID veloce', 'MP11');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'RIBA', 'MP12');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'MAV', 'MP13');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Quietanza erario', 'MP14');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Giroconto su conti di contabilità speciale', 'MP15');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Domiciliazione bancaria', 'MP16');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Domiciliazione postale', 'MP17');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Bollettino di c/c postale', 'MP18');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'SEPA Direct Debit', 'MP19');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'SEPA Direct Debit CORE', 'MP20');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'SEPA Direct Debit B2B', 'MP21');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Trattenuta su somme già riscosse', 'MP22');
COMMIT;
