INSERT INTO tipo_pagamento VALUES (DEFAULT, 'contanti', 'MP01');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'assegno', 'MP02');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'assegno circolare', 'MP03');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'contanti presso Tesoreria', 'MP04');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'bonifico', 'MP05');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'vaglia cambiario', 'MP06');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'bollettino bancario', 'MP07');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'carta di pagamento','MP08');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'RID', 'MP09');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'RID utenze', 'MP10');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'RID veloce', 'MP11');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'RIBA', 'MP12');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'MAV', 'MP13');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'quietanza erario', 'MP14');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'giroconto su conti di contabilità speciale', 'MP15');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'domiciliazione bancaria', 'MP16');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'domiciliazione postale', 'MP17');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'bollettino di c/c postale', 'MP18');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'SEPA Direct Debit', 'MP19');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'SEPA Direct Debit CORE', 'MP20');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'SEPA Direct Debit B2B', 'MP21');
INSERT INTO tipo_pagamento VALUES (DEFAULT, 'Trattenuta su somme già riscosse', 'MP22');
